#!/bin/bash
# generate-secrets.sh - Generate secure secrets for development environment
# Usage: ./generate-secrets.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.development"

echo "🔐 Generating secure secrets for development environment..."

# Generate random passwords
POSTGRES_PASSWORD=$(openssl rand -base64 32)
REDIS_PASSWORD=$(openssl rand -base64 32)
MINIO_ROOT_PASSWORD=$(openssl rand -base64 32)
JWT_SECRET=$(openssl rand -hex 32)

# Create or update .env.development file
cat > "$ENV_FILE" << EOF
# Development Environment Configuration
# Generated by generate-secrets.sh
# DO NOT commit this file to version control

# PostgreSQL
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Redis
REDIS_PASSWORD=${REDIS_PASSWORD}

# MinIO
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}

# JWT
JWT_SECRET=${JWT_SECRET}

# Application
SERVER_PORT=8080
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432/photo_audit?sslmode=disable
REDIS_URL=redis://:${REDIS_PASSWORD}@localhost:6379
MINIO_ENDPOINT=localhost:9000
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET=audit-platform
FALLBACK_ENABLED=true
EOF

chmod 600 "$ENV_FILE"

echo "✅ Secrets generated and saved to .env.development"
echo ""
echo "📝 Next steps:"
echo "   1. Review the generated secrets in .env.development"
echo "   2. Update docker-compose.yml to use these secrets"
echo "   3. Run: docker compose up -d"
